"""Phase-4 developer-set hand annotations (HUMAN REVIEW).

The developer set is the labelled TRAIN/VAL/TEST source for Phase-4 baselines.
It is conversation-disjoint from the 200-example golden benchmark.

Every key is a REAL conversation_id (100 screened-but-not-golden Phase-3
candidates + 100 deterministically sampled corpus conversations; see
data/golden/dev_ids.json). Labels are HUMAN-assigned by reading the current
message + conversation_context together, following
config/amazon_intent_guidelines.yaml. None are keyword-derived.

Schema (see config/amazon_intent_guidelines.yaml):
  lang / primary (12-intent id | none | other_unclear)
  secondary (genuinely co-occurring intents)
  mtype / ctx / difficulty / conf / note
"""
# fmt: off
DEV = {
    43713: dict(lang="ja", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Wistful comment wishing Kindle were more convenient; no actionable issue."),
    99899: dict(lang="es", primary="none", secondary=[], mtype="support_request",
        ctx="context_required", difficulty="hard", conf="medium", note="Asks to DM about 'an account problem' without specifying which; intent undetermined."),
    122705: dict(lang="ja", primary="cancellation", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Package turned up but customer says they did not order it (did-not-order)."),
    124763: dict(lang="ja", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Skirt wrinkled because packaging was terrible; damaged-product complaint."),
    132555: dict(lang="de", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Prime shipping used to be faster; delivery date later than expected."),
    142875: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Light-hearted comment about buying an Echo; no issue."),
    144159: dict(lang="ja", primary="other_unclear", secondary=[], mtype="unknown",
        ctx="context_required", difficulty="hard", conf="low", note="'I am defeated / no idea' - no subject; cannot map to an intent."),
    160274: dict(lang="pt", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Black Friday promo mention; not a support issue."),
    160437: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="medium", note="'Thanks.' - ack; context shows an order-progress thread but current msg is a thanks."),
    167910: dict(lang="fr", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks whether Switch price will drop below 292EUR; pre-purchase pricing question."),
    169499: dict(lang="es", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Price reverted to normal in cart during Black Friday; price discrepancy."),
    179089: dict(lang="fr", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="24h delivery but 48h to take charge; delay complaint."),
    179430: dict(lang="en", primary="other_unclear", secondary=[], mtype="support_request",
        ctx="context_required", difficulty="hard", conf="low", note="'I need urgent help??' with no subject; cannot map to an intent."),
    204928: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="Positive praise about Prime Music; no issue."),
    215983: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Pure thank-you for fast responses."),
    218049: dict(lang="en", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="medium", note="Pre-order listing not showing in the app = app/listing problem."),
    231507: dict(lang="ja", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Informational question about Kindle Unlimited vs Prime Reading."),
    234234: dict(lang="es", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="medium", conf="medium", note="Comments that seller Q&A info in a listing is still wrong; informational, not a domain intent."),
    245210: dict(lang="de", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Carrier not keeping delivery times; delay complaint."),
    245874: dict(lang="es", primary="delivered_but_not_received", secondary=["refund_request"], mtype="clarification",
        ctx="context_required", difficulty="hard", conf="medium", note="Answers who the seller was; context shows paid product not delivered + refund ask."),
    2516925: dict(lang="ja", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Adding to wishlist from iPad web auto-adds to cart; browser/app bug."),
    2520585: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Joined Prime, happy Glee cast is streamable; no issue."),
    2533178: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Hopes Echo Dot ships from a local centre; informational, no issue."),
    2539036: dict(lang="en", primary="refund_request", secondary=[], mtype="complaint",
        ctx="context_required", difficulty="hard", conf="low", note="'Go to hell' venting; context is a blocked/timely refund ask."),
    2540322: dict(lang="fr", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Ok merci bcp!' - ack; context is a point-relais delivery check."),
    2549840: dict(lang="en", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Complaint about a radio piece repeating 'Alexa'; not a support intent."),
    2567029: dict(lang="en", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Wasteful-but-received order; complains about oversized box (sustainability)."),
    2571862: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Will do. Thanks.' - ack; context is a delivery-delay thread."),
    2573764: dict(lang="fr", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Charged for 2 electric toothbrushes not ordered nor received."),
    2587901: dict(lang="es", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="USB gold card not accepted for monthly installments on a TV; payment issue."),
    2596396: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="'Alrdy done' + context: rep used rude words; wants apology + escalation."),
    2611640: dict(lang="en", primary="charge_issue", secondary=["cancellation"], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Cancelled Prime but payment still collected after cancellation."),
    2615198: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="'This is what the seller delivers' - shows a bad/damaged product from a seller."),
    2616364: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks whether an order qualifies for No-Cost EMI; payment-option question."),
    2641344: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_required", difficulty="hard", conf="medium", note="'UPS' answers carrier; context shows out-for-delivery all day, still not arrived."),
    2646224: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Package still not arrived; 'first time Amazon failed me'."),
    2710825: dict(lang="en", primary="device_app_issue", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Echo Look feature-set differences question; informational app query."),
    271574: dict(lang="ja", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Wrong/misdescribed product; applied for a return; venting."),
    275517: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Happy cosmetics arrived; no issue."),
    2762698: dict(lang="it", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="Package (warranty repair) stuck in transit at Piacenza."),
    277573: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Wants to pick up package personally; frustrated about delivery."),
    2793099: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Courier tried to deliver to a school at 9pm; order already a day late."),
    2813544: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Package was stolen today."),
    2828095: dict(lang="fr", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Received a book in bad condition."),
    282811: dict(lang="ja", primary="product_return_and_replacement", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Refund processing but asks item be re-sent; replacement/re-ship request."),
    2830752: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="'worst customer service'."),
    2837028: dict(lang="pt", primary="product_return_and_replacement", secondary=["service_complaint_escalation"], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Sold economy-version books without notice; wrong/undisclosed edition."),
    2838599: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Disappointed with phone customer service."),
    2875661: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="28 days, no firm answer, kept being asked to fill forms; support complaint."),
    2876322: dict(lang="en", primary="service_complaint_escalation", secondary=["product_return_and_replacement"], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Slow/painful return policy; #neveragain."),
    2881862: dict(lang="es", primary="account_info_update", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Needs to change billing address, help options don't work."),
    2885720: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Ordered drone 16th Oct, still not received; no confidence in new date."),
    2899717: dict(lang="en", primary="charge_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Digital service charge appeared but doesn't know why."),
    2925496: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="No email about package; status now 'in two days'."),
    2931916: dict(lang="ja", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Praise: Amazon Music Unlimited 'changed the world'."),
    2939131: dict(lang="de", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Business-account contact question; context shows a premium-delivery concern."),
    2942015: dict(lang="en", primary="cancellation", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="medium", conf="low", note="Asks whether ordering another G5s Plus would get cancelled (purchase-limit worry)."),
    2952251: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Drivers only allow ~3 seconds to answer the door before driving off."),
    2962808: dict(lang="en", primary="charge_issue", secondary=["delivery_delay"], mtype="complaint",
        ctx="context_required", difficulty="hard", conf="medium", note="Paid $30 extra for 1-day shipping but effectively 2-day; price/service gripe."),
    2971950: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Okay thank you' - ack; context is a sign-out/account question."),
    2976516: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Driver claimed could not contact despite customer calling 3 times; scan issue."),
    2986458: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks how to join Amazon Family; informational membership question."),
    304554: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="medium", conf="medium", note="Third-party SELLER question about unique listings; not a customer support intent."),
    307901: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Thanks!' ack re light-ring/notification status."),
    316306: dict(lang="en", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="low", note="Delivered but no installation call; installation-service concern fits no intent."),
    332782: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Complaint that support reps get angry when asked to clarify."),
    351165: dict(lang="ja", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Venting that COD isn't available for some items (credit only); payment-method gripe."),
    382580: dict(lang="fr", primary="delivered_but_not_received", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="Package returned to sender due to sorting error; never received it."),
    388854: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Package stuck at hub, not delivered despite status."),
    404092: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="Hearts/thanks; context shows successful replacement + praise."),
    407498: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="'Haven't gotten a single thing on time' - delay."),
    411435: dict(lang="en", primary="cancellation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Book bought automatically (accidental purchase); did-not-intend-to-order."),
    414010: dict(lang="ja", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Order waited for 2 weeks (slow)."),
    420425: dict(lang="en", primary="refund_request", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Direct refund request for an order."),
    428614: dict(lang="en", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="low", note="Complaint about Amazon selling a controversial product; not a support intent."),
    436337: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Out-for-delivery status looks fake; repeated delivery failures."),
    437366: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Mobile delivered to someone else; no response from support."),
    470156: dict(lang="en", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Irritated by marketing emails; not a domain support intent."),
    471605: dict(lang="ja", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Order for Hokkaido delivered to Shimane (wrong place)."),
    502468: dict(lang="es", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Feature suggestion for an app/web section; not a bug or support intent."),
    535015: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Contradictory courier updates; not delivered despite promises."),
    542144: dict(lang="es", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Gift promised yesterday, arrived neither yesterday nor today; delay."),
    566690: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="medium", note="'UPS' answers carrier question; context shows package 2 days late."),
    576056: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Shout-out/praise for a wreath delivery; no issue."),
    605115: dict(lang="ja", primary="delivered_but_not_received", secondary=[], mtype="acknowledgement",
        ctx="context_required", difficulty="hard", conf="medium", note="Current msg 'just arrived'; context shows it previously showed delivered when it wasn't."),
    619219: dict(lang="es", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Pantry order took 8 days / not shipped; delay."),
    619972: dict(lang="es", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="'NO ME HA LLEGADO' - not received."),
    663814: dict(lang="es", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Positive about using ____ with Amazon Prime."),
    674259: dict(lang="en", primary="delivered_but_not_received", secondary=["refund_request"], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="high", note="Items lost in post; asks to open a lost-item claim / refund."),
    71873: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="low", note="Sarcastic venting about mixed-up return-pickup timing; service complaint."),
    719853: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="'good job' praise."),
    728121: dict(lang="en", primary="refund_request", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Returned item 2 weeks ago, still no refund."),
    74611: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="context_required", difficulty="hard", conf="medium", note="Current message is an influencer pitch; context shows an unresolved bad-product/return thread."),
    746831: dict(lang="en", primary="other_unclear", secondary=[], mtype="unknown",
        ctx="context_required", difficulty="hard", conf="low", note="'Received a strange email' - suspicious but no account issue confirmed."),
    758987: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Gift arrived crushed/damaged; can't return in time for tomorrow."),
    764802: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Courier left books in cardboard in the rain (exposed)."),
    783437: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Got notification package received but did not receive it."),
    832367: dict(lang="de", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Complains carriers park in no-stopping/fire-access zones; not a support intent."),
    840845: dict(lang="ja", primary="product_return_and_replacement", secondary=["delivery_delay"], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="medium", note="Defective item replacement via China took 2 weeks, then returned 'addressee unknown'."),
    858760: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Sick of waiting for a call; can't post reviews/questions in community."),
    870091: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Doubts the 'not reachable / heavy rain' excuse for failed delivery."),
    896646: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks about mobile giveaways during a festival."),
    897110: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="clarification",
        ctx="context_required", difficulty="hard", conf="medium", note="Answers that details were emailed; context shows frustration/goodbye over poor support."),
    907087: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Pre-order failed to be delivered."),
    947732: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="#UnlimitedScreaming promo participation; no issue."),
    956263: dict(lang="fr", primary="none", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="low", note="Chases 'do you have a response yet' with no subject; intent undetermined."),
    964223: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Complains about 'worst services'; asks for help."),
    980000: dict(lang="ja", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Asks if 11-digit payment number is in order history; informational."),
    1005058: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="context_required", difficulty="hard", conf="low", note="'you have a DM' - pointer, intent unknown."),
    1009216: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Waited all day for 'out for delivery', never turned up; had to call for refund."),
    1059308: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Executives not providing right assistance."),
    1085206: dict(lang="de", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="medium", conf="medium", note="Aside venting about Twitch Prime; not a support intent."),
    1093291: dict(lang="de", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Informational question about watching series with English subtitles."),
    1100448: dict(lang="de", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="easy", conf="high", note="Humorous aside about '120 shipments' (typo joke); no issue."),
    1103613: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Package marked delivered but was not."),
    1106537: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Says #AmazonPrimeNEVER; watched driver go the wrong way after ordering."),
    1112663: dict(lang="fr", primary="delivered_but_not_received", secondary=[], mtype="clarification",
        ctx="context_required", difficulty="hard", conf="medium", note="Answers 'Amazon Logistics' (carrier); context shows shows-delivered-but-nothing."),
    1152679: dict(lang="es", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Package delivered to another person; replacement sent but venting."),
    1160398: dict(lang="pt", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Credit-card payment problem caused a discounted purchase to be lost."),
    1165671: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="high", note="'Thank you!' ack; context shows account-locked support thread but current msg is thanks."),
    1171368: dict(lang="de", primary="order_status_query", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Asks if a preordered product will still arrive on Friday around a holiday."),
    1177138: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Sarcastic thanks; jewellery left on doorstep at 8:30pm (exposed)."),
    1195807: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks about iPad Split View support; informational app question."),
    1198272: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Paid extra for faster service, reason given 'it stopped'."),
    1200067: dict(lang="de", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="high", note="Can't find the Alexa 'Routines' function."),
    1208413: dict(lang="ja", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="context_required", difficulty="hard", conf="low", note="'Man lied to by Amazon' with a link; no details, cannot map."),
    1213413: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Shares a wishlist link; informational, not a domain intent."),
    1219141: dict(lang="es", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Preorder 'guaranteed launch-day delivery' missed; asks for compensation."),
    1221827: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Asks whether Kindle-Audio two-way switch is possible; informational."),
    1223522: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Stated safe place not used by delivery driver."),
    1232177: dict(lang="en", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="low", note="Seller-account funds not being paid out; mapped best-effort to money-not-received."),
    1234099: dict(lang="de", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="'Done.' + small feedback that a link isn't phone-friendly."),
    1261655: dict(lang="en", primary="charge_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="high", note="Gift card expired while changing payment option; wants to reuse it."),
    1261878: dict(lang="en", primary="delivery_delay", secondary=[], mtype="clarification",
        ctx="context_required", difficulty="hard", conf="medium", note="Asks what other info is needed; context shows undelivered order (driver never called)."),
    1307226: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Delivery date slipped from the 18th to '1.5 weeks'."),
    1308262: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Packages left sitting in the 4th-floor hallway of an office building."),
    1323412: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Sarcastic book title 'How to not help a Customer' about support."),
    1339609: dict(lang="fr", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="😘😘😘 - playful ack/emoji."),
    1343595: dict(lang="fr", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="context_required", difficulty="hard", conf="medium", note="'Nothing in the mailbox' - implies an awaited delivery not received."),
    1364737: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Lyrics function seemingly removed with latest firmware (music app)."),
    1380925: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Prime 1-day promise vs 3-4 days shown at order time."),
    1386473: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Happy about an Echo arriving Friday; not an issue."),
    1390714: dict(lang="de", primary="delivered_but_not_received", secondary=["refund_request"], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Package lost (replacement not possible) yet asked to return items for refund."),
    1394424: dict(lang="en", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="low", note="Delivery agent asked the customer to come and collect the parcel; conduct concern."),
    1424922: dict(lang="ja", primary="order_status_query", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="medium", note="Order disappeared from order history; asks why."),
    1429494: dict(lang="en", primary="order_status_query", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks to escalate an order and share the status."),
    1436676: dict(lang="fr", primary="product_return_and_replacement", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks for information on returning a product."),
    1453811: dict(lang="de", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="Package due yesterday, tracking 40-50km away; asks what to do."),
    1466972: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Parcel promised out-for-delivery then 'we don't know where it is'; 4 days wasted."),
    1488377: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="'What's wrong with the world's most customer-centric company' - disappointed."),
    1519126: dict(lang="es", primary="account_access", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Can't log into their account."),
    1548344: dict(lang="en", primary="none", secondary=[], mtype="clarification",
        ctx="context_required", difficulty="hard", conf="low", note="'Yes, I have.' answers a form/completion question; underlying issue unknown."),
    1551311: dict(lang="en", primary="other_unclear", secondary=[], mtype="support_request",
        ctx="context_required", difficulty="hard", conf="low", note="'hey i need help' - no subject."),
    1565868: dict(lang="en", primary="service_complaint_escalation", secondary=["delivery_delay"], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Rude, cut-off calls + failed twice to deliver prime."),
    1572899: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Fake 11:54pm 'delivery attempt' looks like courier fraud."),
    1598729: dict(lang="ja", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="Past expected date, asked to wait until a later date, still not delivered."),
    1604131: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Feature feedback re sorting movies by language in Prime Video."),
    1616279: dict(lang="ja", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Brother's game was crushed before it was even opened (damaged)."),
    1622253: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Past Oct 16, prime order takes 7 days and still not delivered."),
    1648054: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Waited all day for parcel expected today."),
    1655018: dict(lang="en", primary="none", secondary=[], mtype="clarification",
        ctx="context_required", difficulty="hard", conf="low", note="'Tell me what detail do you need' - asks for requirements; intent unknown."),
    1663547: dict(lang="fr", primary="account_access", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Concerned client data was hacked (phishing email / account security)."),
    1684961: dict(lang="ja", primary="order_status_query", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="low", note="Payment number for a preorder not being sent; order-processing issue."),
    1693690: dict(lang="en", primary="charge_issue", secondary=["refund_request"], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Charged extra amount; wants refund and compensation."),
    1718328: dict(lang="en", primary="refund_request", secondary=["product_return_and_replacement", "service_complaint_escalation"], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Defective item returned, no refund/update; poor service."),
    1741712: dict(lang="en", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Help with #AmazonVideo (streaming app)."),
    1770463: dict(lang="es", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks how to obtain an invoice file; informational."),
    1780206: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks whether an Echo can be restricted to one person; informational."),
    1806474: dict(lang="ja", primary="order_status_query", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="Doesn't know when a preorder will arrive; worried."),
    1827324: dict(lang="ja", primary="account_access", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Account apparently hijacked; asks what to do."),
    1850390: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Next-day became two days, now 'between now and the 31st'; 'where's my shit'."),
    1877582: dict(lang="ja", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="medium", conf="medium", note="Commentary about forgetting to cancel Prime (auto-renew); not a current action request."),
    1910321: dict(lang="de", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Receives fake 'order confirmation' phishing emails; hasn't ordered."),
    1912587: dict(lang="pt", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Asks when a box set will be sold in Brazil; availability question."),
    1968370: dict(lang="en", primary="cancellation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Order showing cancelled when they didn't cancel it."),
    2052149: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="'Done! Thanks' - ack."),
    2061567: dict(lang="en", primary="cancellation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Tricked into something unwanted; wants to cancel immediately."),
    2089262: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Happy gifts arrived fast; no issue."),
    2093938: dict(lang="hi", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="low", note="Company 'cheats 2000 rupees'; order returned and asked to reorder at 12999 vs 10999."),
    2162437: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Package damaged in transit; asked to reorder and wait 10 days."),
    2208276: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="low", note="'Have to wait until the 13th to play it' - release/delivery wait; context-limited."),
    2213169: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Driver drove off without delivering; no item."),
    2220210: dict(lang="de", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="'Need goods today and not Monday' - delivery delay."),
    2277148: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Charged for 2-day shipping, items don't arrive in 2 days."),
    2278758: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Prime items never arrive in two days."),
    2286003: dict(lang="en", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Complains about wasteful/ridiculous packaging."),
    2291005: dict(lang="en", primary="refund_request", secondary=["delivery_delay"], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="high", note="Paid extra postage, only half arrived on time; asks postage refund."),
    2312754: dict(lang="en", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="A rep gave Prime to fiancé then charged card without consent."),
    2342084: dict(lang="en", primary="device_app_issue", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="How to connect Spotify to Echo; why Alexa doesn't search Google."),
    2349567: dict(lang="pt", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="easy", conf="high", note="Joke about browsing Amazon; no issue."),
    2350925: dict(lang="en", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="low", note="'Still do not have my reputation copy' - item unclear."),
    2352338: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Updated 'delivered', no agent/no parcel; shows delivered but not received."),
    2360502: dict(lang="en", primary="none", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="low", note="Shared contact details + problems; waiting for response; subject unknown."),
    2383229: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Received a Bluetooth speaker; praise."),
    2398918: dict(lang="en", primary="account_access", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Account hacked and password changed without consent."),
    2408722: dict(lang="en", primary="service_complaint_escalation", secondary=["delivery_delay"], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="'Stop assuring, 7 agents did that today' - delivery not on time + poor support."),
    2416355: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Struggled to find the contact/chat option re an order; not user friendly."),
    2450867: dict(lang="en", primary="none", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="COD not available for their address though it is for others; payment-method gripe."),
    2472404: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Two items to return; locker reservation question."),
    2483748: dict(lang="en", primary="refund_request", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="No response after 7 days; context is a refund/replace-as-lost chase."),
}
