"""Phase-3 hand-authored golden annotations (HUMAN REVIEW).

Assigned by reading each current-customer message + conversation-context together.
Every key is a REAL conversation_id drawn from the Phase-3 candidate pools
(verified programmatically against the pool files). Labels are NOT keyword-derived.

Key schema (see config/amazon_intent_guidelines.yaml):
  lang / primary (12-intent id | none | other_unclear)
  secondary (list of genuinely co-occurring intents)
  mtype / ctx / difficulty / conf / note

Composition: 150 representative (140 English rep-pool + 10 standard English
challenge) + 50 challenge (25 non-English + 25 hard English).
"""
# fmt: off
REPRESENTATIVE = {
    # --- delivery / fulfilment ---
    458877: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Arriving-8pm window passing; no shipment/tracking."),
    142833: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Out for delivery / due but overdue; chases status."),
    1116569: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Paid 1-day, not arrived."),
    515245: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Due Wednesday, still missing Friday."),
    2447788: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Due 31 Oct, not delivered by 14 Nov."),
    2960467: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Two-day prime turned into a week."),
    1311577: dict(lang="en", primary="delivery_delay", secondary=["order_status_query"],
        mtype="follow_up", ctx="self_contained", difficulty="medium", conf="high", note="Where is it for a late order."),
    608064: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Delivery date repeatedly pushed back."),
    2967623: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Package late beyond promised day."),
    2528270: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="One-day-shipping options disappeared; promise missed."),
    2683519: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Prime Pantry 'delivered' actually at USPS; delay/not-received."),
    1192307: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Van pulled up then left; not delivered."),
    2780552: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Told to wait longer for delivery."),
    2824739: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Questions meaning of 'one day delivery'."),
    2913230: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="easy", conf="high", note="Prime items due Thursday; why 2-day delay."),
    1218249: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="UPS tracking shows shipping delay."),
    2003910: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="'Taken care of' should have meant Friday delivery."),
    300514: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Prime next-day not honored."),
    322945: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Prime preference/2-day promise not met."),
    2954293: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Prime not reliable/fast; delivery promise missed."),
    2664071: dict(lang="en", primary="delivery_delay", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="low", note="Mixed ad complaint + prime not fast; ambiguous."),
    1210214: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Package returned to courier; driver refused delivery."),
    86209: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Prime gift promised today, not arrived."),
    2192580: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="No tracking updates; supposed to arrive yesterday."),
    1406593: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="low", note="'First weekend of prime, not impressed'; delay presumed."),
    1570766: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Any update on delivery."),
    1389974: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Asks to arrange/provide parcel."),
    1399860: dict(lang="en", primary="delivery_delay", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Thanks + kindly arrange my parcel."),
    1721707: dict(lang="en", primary="order_status_query", secondary=["delivery_delay"],
        mtype="complaint", ctx="self_contained", difficulty="medium", conf="medium", note="Paid next-day, not delivered; status/delay overlap."),
    646730: dict(lang="en", primary="order_status_query", secondary=["delivery_delay"],
        mtype="follow_up", ctx="context_helpful", difficulty="medium", conf="medium", note="When will it dispatch; overdue dispatch."),
    2363235: dict(lang="en", primary="order_status_query", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="high", note="Tracking discrepancy amazon vs USPS."),
    2960026: dict(lang="en", primary="order_status_query", secondary=[], mtype="follow_up",
        ctx="self_contained", difficulty="medium", conf="high", note="TV went to UPS then back; where is it."),
    1105754: dict(lang="en", primary="order_status_query", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Order-update timestamps wrong (GMT)."),
    1464285: dict(lang="en", primary="order_status_query", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Will my order be shipped?"),
    1893565: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Never received promised call back."),

    # --- delivered but not received / wrong location ---
    1109519: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Routinely marked delivered before attempt; some never arrive."),
    1423023: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Courier marked delivered then kept parcel in van."),
    2289844: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Agent marks delivered without actual delivery."),
    1220925: dict(lang="en", primary="delivered_but_not_received", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="medium", conf="high", note="Listed delivered but not here; 'why do nothing'."),
    2532842: dict(lang="en", primary="delivered_but_not_received", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Undelivered parcel 2 weeks; fed up."),
    380695: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Package 'lost or damaged'; not received."),
    482351: dict(lang="en", primary="delivered_but_not_received", secondary=["product_return_and_replacement"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Marked delivered, part missing, box partly open."),
    533206: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Driver left parcel in exposed recycle bin without consent."),
    149199: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Parcel left in unsafe spot despite note."),
    2283511: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="5 packages 'delivery attempted' to wrong area."),
    2594956: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Package at risk near open doors; unattended drop."),

    # --- refunds / cancellation / charge ---
    18706: dict(lang="en", primary="refund_request", secondary=["product_return_and_replacement"],
        mtype="support_request", ctx="context_helpful", difficulty="medium", conf="high", note="Returned wrong product; demands refund."),
    1436650: dict(lang="en", primary="refund_request", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Promised refund, now denied."),
    2712534: dict(lang="en", primary="refund_request", secondary=["delivered_but_not_received"],
        mtype="support_request", ctx="context_helpful", difficulty="medium", conf="medium", note="Prime Now missing items; cannot find refund path."),
    1420491: dict(lang="en", primary="refund_request", secondary=["cancellation"],
        mtype="follow_up", ctx="context_helpful", difficulty="medium", conf="high", note="Cancelled product; refund to CC."),
    915961: dict(lang="en", primary="refund_request", secondary=["service_complaint_escalation"],
        mtype="follow_up", ctx="context_helpful", difficulty="medium", conf="medium", note="Awaiting refund; number blocked."),
    1604096: dict(lang="en", primary="charge_issue", secondary=["refund_request"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Money sent to a closed bank account; refund/charge."),
    1218305: dict(lang="en", primary="charge_issue", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="low", note="Money taken, asked to cancel; ambiguous charge/cancel/service."),
    22572: dict(lang="en", primary="cancellation", secondary=["refund_request"],
        mtype="support_request", ctx="self_contained", difficulty="medium", conf="high", note="Not delivered; no way to cancel and get refund."),
    2899649: dict(lang="en", primary="cancellation", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="high", note="Going to cancel the order; done waiting."),
    136922: dict(lang="en", primary="cancellation", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Cancelled whole order; wants an email address."),
    1724691: dict(lang="en", primary="charge_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Money debited but not credited to Amazon Pay."),
    2612309: dict(lang="en", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Card overdrawn from something not bought on Amazon."),
    332434: dict(lang="en", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="COD available but fails at checkout; payment option issue."),
    895946: dict(lang="en", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Cart price jumped above regular; price discrepancy."),
    2515914: dict(lang="en", primary="refund_request", secondary=["service_complaint_escalation"],
        mtype="follow_up", ctx="context_helpful", difficulty="medium", conf="medium", note="Argues for Prime refund on three orders."),
    2217342: dict(lang="en", primary="refund_request", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Claim rejected, seller sketchy."),
    467536: dict(lang="en", primary="product_return_and_replacement", secondary=["charge_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="App hid T&C; lost cashback; item not received."),

    # --- return / replacement ---
    1147828: dict(lang="en", primary="product_return_and_replacement", secondary=["refund_request"],
        mtype="follow_up", ctx="context_helpful", difficulty="hard", conf="medium", note="No-cost EMI return/refund friction."),
    2454046: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="Started a return and reordered a wrong item."),
    679025: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="high", note="Wrong colour Kindle; asks to exchange."),
    2460750: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Ordered G5s, got G5plus; wrong item."),
    2450570: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Sent wrong cases."),
    2608094: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Item missing parts; contact to get rest."),
    982267: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Ordered altitude mask, received a tutu."),
    2291505: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Defective display; wants replacement."),
    1018235: dict(lang="en", primary="product_return_and_replacement", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Wrong product; forced to self-ship return."),
    1229460: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="DVD fraud (wrong version)."),
    2484077: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Faulty cup received."),
    345473: dict(lang="en", primary="product_return_and_replacement", secondary=["device_app_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Device keeps malfunctioning; replacements faulty."),

    # --- device / app ---
    1229688: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Kindle app text broken after reinstall."),
    26958: dict(lang="en", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Alexa app down/timing out in London."),
    2378990: dict(lang="en", primary="device_app_issue", secondary=["charge_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Alexa reports a price different from listing."),
    1384330: dict(lang="en", primary="device_app_issue", secondary=["charge_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Payment issue inside Amazon app."),
    2523357: dict(lang="en", primary="device_app_issue", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Echo Dot alarm suddenly quiet."),
    1766849: dict(lang="en", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Fire Stick/Android box streaming issue."),
    2847379: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Alexa language setting unavailable in Canada."),
    2569705: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Timing out across the board; outage."),
    350494: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Echo sold without Alexa app for India."),

    # --- account ---
    1912145: dict(lang="en", primary="account_access", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Wants purchase history hidden/password; access/privacy."),
    179205: dict(lang="en", primary="account_access", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="easy", conf="high", note="Can't log in for a day."),
    2789138: dict(lang="en", primary="account_access", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="hard", conf="low", note="Check if signed up to Prime; membership status."),
    427799: dict(lang="en", primary="account_info_update", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="low", note="Ask about paying prime with Amazon Pay balance."),

    # --- service complaint / escalation ---
    1763226: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="8 hours on live chat, got nowhere."),
    2573750: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Called support number 5 times, nothing."),
    1541879: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Support says can't deal with me; email not recognised."),
    1415560: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Rep call was useless; still disappointed."),
    334873: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="6 years, first issue; 10 mins no reply."),
    272875: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="No support link given; pinging here."),
    1537572: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Hard to report a shipping problem."),
    411902: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Never use Amazon for business; bad CS."),
    1588773: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Service getting worse; may dump Amazon."),
    2353843: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Called 5 times, no resolution; wants phone call."),
    1136222: dict(lang="en", primary="service_complaint_escalation", secondary=["delivery_delay"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="50 calls, no response; fake commitment."),
    1384189: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Bad experience, no customer service."),
    1746071: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Impossible to reach customer care by phone."),
    390810: dict(lang="en", primary="service_complaint_escalation", secondary=["charge_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="low", note="Payment done, nasty excuses; angry, ambiguous."),
    2151408: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Denied basic GST input credit; complaining."),
    2216600: dict(lang="en", primary="service_complaint_escalation", secondary=["charge_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Cashback offers not honored; complaint."),
    1250967: dict(lang="en", primary="service_complaint_escalation", secondary=["delivered_but_not_received","charge_issue"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Lost packages + wrong charges; 'point of prime'."),
    2447260: dict(lang="en", primary="service_complaint_escalation", secondary=["delivery_delay"],
        mtype="complaint", ctx="context_helpful", difficulty="medium", conf="medium", note="USPS deliveries never on time; complaint."),
    1179639: dict(lang="en", primary="service_complaint_escalation", secondary=["delivered_but_not_received"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Agents contradict each other; locker item."),
    1943693: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Yes I've shared the concern' — ack/confirmation."),
    2245407: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Calls dropped; wants call log checked."),
    993935: dict(lang="en", primary="order_status_query", secondary=["service_complaint_escalation"],
        mtype="follow_up", ctx="context_helpful", difficulty="medium", conf="medium", note="Searching for product + delivery response."),

    # --- none / conversational ---
    2611658: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Got the package, thanks'."),
    309233: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Thanks for cat bed; praise."),
    2111184: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Praise for quick response."),
    174486: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Made me very happy today'."),
    2580464: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Good rep in chat now; praise—resolved."),
    2855145: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Resolution thanks (was sales tax)."),
    2384553: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="easy", conf="high", note="Books on the way; excited ack."),
    1198549: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="Respect for postal service; ack."),
    1204940: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Yes absolutely right' — ack."),
    487699: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="Resolved mistake; sorry for inconvenience."),
    1181640: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Will do, thank you' — ack."),
    628261: dict(lang="en", primary="none", secondary=[], mtype="clarification",
        ctx="context_required", difficulty="medium", conf="medium", note="'Guessing marketplace seller?' — answering brand question."),
    2931934: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="hard", conf="low", note="Wants an iphone as a gift without purchase; unclear."),
    2769011: dict(lang="en", primary="none", secondary=[], mtype="clarification",
        ctx="context_helpful", difficulty="medium", conf="medium", note="No need to fill form, sharing email via DM."),
    1755281: dict(lang="en", primary="other_unclear", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="hard", conf="low", note="Reports a suspicious phishing-style email; no intent fits cleanly."),
    1707062: dict(lang="en", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="Mystery solved, thanks."),
    957126: dict(lang="en", primary="none", secondary=[], mtype="clarification",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Responds re device region; clarification."),
    832924: dict(lang="en", primary="order_status_query", secondary=["delivery_delay"],
        mtype="follow_up", ctx="context_helpful", difficulty="medium", conf="medium", note="Revised delivery date vs in-stock discrepancy."),
    1335118: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Order placed 24th, not shipped; needed for trip."),
    2389800: dict(lang="en", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="hard", conf="low", note="Generic product marketing text, no intent."),
    676899: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Unfulfilled Blu-ray order; product/order complaint."),
    880948: dict(lang="en", primary="cancellation", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Pickup cancelled without proper call; courier complaint."),
    999138: dict(lang="en", primary="delivery_delay", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="medium", conf="medium", note="Prime let down; will cancel subscription; delivery delay."),
    650056: dict(lang="en", primary="cancellation", secondary=["refund_request"],
        mtype="follow_up", ctx="context_helpful", difficulty="hard", conf="medium", note="Cancel prime and refund last charge."),

    # --- 10 standard-English challenge examples added to representative ---
    2852150: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Waiting at door for expected delivery."),
    2890574: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Prime 2-day often not met; service degraded."),
    1420099: dict(lang="en", primary="delivery_delay", secondary=["refund_request"],
        mtype="complaint", ctx="context_helpful", difficulty="medium", conf="medium", note="Three items' delivery dates pushed; wants refund."),
    550560: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Prime 1-2 day shipping arrives 3-5+ days."),
    673242: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Order late; told it'd be here tomorrow."),
    1193931: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Carrier named; unclear if tomorrow or delayed."),
    2731105: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Paid same-day, delivered tomorrow."),
    2288190: dict(lang="en", primary="order_status_query", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Same-day order not yet shipped; wants to know when."),
    2374486: dict(lang="en", primary="order_status_query", secondary=["delivered_but_not_received"],
        mtype="complaint", ctx="self_contained", difficulty="hard", conf="medium", note="'Delivered by 8pm' but 'not yet shipped' contradiction."),
    1397273: dict(lang="en", primary="order_status_query", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="When will Echo Spot launch in India."),
    1727624: dict(lang="en", primary="delivered_wrong_location", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="How to contact about a stolen package."),
    1587374: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Scheduled 3 Nov, still not received."),
    2296826: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="high", note="Royal Mail didn't deliver; order delayed."),
    1464161: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Prime Video episode still unavailable."),
    2266765: dict(lang="en", primary="none", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="high", note="Asks about upcoming sale / help; no domain intent."),
    886169: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Terrible short email, no instructions/voice mails."),
}

CHALLENGE = {
    # --- non-English (multilingual oversample) ---
    487688: dict(lang="fr", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Ordered Sunday received Friday; 'better late than never' — ack."),
    1451501: dict(lang="pt", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="high", note="First purchase praise; no intent."),
    787658: dict(lang="es", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="high", note="'Thanks, everything resolved' — ack."),
    893308: dict(lang="pt", primary="none", secondary=[], mtype="unknown",
        ctx="context_helpful", difficulty="hard", conf="low", note="Vague spending-related post; no clear intent."),
    2254596: dict(lang="it", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Grazie, buonanotte' — ack."),
    1578555: dict(lang="de", primary="delivered_wrong_location", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Both packages delivered to wrong person."),
    2609965: dict(lang="fr", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="low", note="Packaging not discreet vs request; no intent fits clearly."),
    2170818: dict(lang="en", primary="delivery_delay", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="medium", note="Needs by tomorrow; tracking late (context)."),
    426141: dict(lang="es", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="medium", conf="high", note="Fast delivery praise; ack."),
    816342: dict(lang="it", primary="none", secondary=[], mtype="unknown",
        ctx="self_contained", difficulty="hard", conf="low", note="Just a hashtag + media link; no intent."),
    2586341: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="medium", conf="high", note="Prime Music value praise; ack."),
    365605: dict(lang="fr", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="high", note="Just received; apologies — resolved ack."),
    842315: dict(lang="fr", primary="delivery_delay", secondary=[], mtype="clarification",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Providing carrier/tracking for late parcel."),
    2472354: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Thanks re Prime membership benefits; ack."),
    1130527: dict(lang="en", primary="order_status_query", secondary=[], mtype="support_request",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Requests invoice print for phone order."),
    1033752: dict(lang="de", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="medium", conf="high", note="Praise for support / arrival; ack."),
    1738390: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="self_contained", difficulty="medium", conf="high", note="Received package, happy — ack."),
    2814438: dict(lang="es", primary="account_access", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Sent fax but account still blocked."),
    582649: dict(lang="en", primary="product_return_and_replacement", secondary=["service_complaint_escalation"],
        mtype="follow_up", ctx="context_helpful", difficulty="hard", conf="low", note="Replacement recurring; multilingual fragment."),
    232399: dict(lang="fr", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="medium", note="Prime/couriers in Paris useless; complaint."),
    834216: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="clarification",
        ctx="context_helpful", difficulty="hard", conf="medium", note="AMZL; delivery guy 'couldn't access' — not received."),
    1955907: dict(lang="en", primary="charge_issue", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="medium", note="Gift-card/voucher validation error."),
    1379340: dict(lang="it", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="high", note="Prime Video app availability on a device."),
    227064: dict(lang="ja", primary="device_app_issue", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="medium", conf="medium", note="Kindle reading access from app."),
    2151072: dict(lang="ja", primary="none", secondary=[], mtype="acknowledgement",
        ctx="context_helpful", difficulty="easy", conf="high", note="'Thank you' — ack."),

    # --- hard English (ambiguous / short / angry / context-dependent) ---
    2171079: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="medium", conf="high", note="Pre-order never arrived; angry."),
    2798309: dict(lang="en", primary="delivered_but_not_received", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="medium", note="Arrival photo in notification vs problem with package."),
    1645512: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Cannot buy on site/app (cart pages)."),
    616914: dict(lang="en", primary="charge_issue", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Repeated £1 auth; no straight answer."),
    689484: dict(lang="en", primary="delivered_but_not_received", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="medium", conf="high", note="Package not delivered; told to file police report."),
    2785904: dict(lang="en", primary="delivery_delay", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Item not left fulfillment center; 'hopefully tomorrow'."),
    2694949: dict(lang="en", primary="account_access", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="hard", conf="low", note="Prime trial unavailable though displayed; membership confusion."),
    2284883: dict(lang="en", primary="delivered_wrong_location", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Neighbor's order misdelivered; distrustful."),
    102915: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Filled form, no hope/no one read it."),
    197857: dict(lang="en", primary="charge_issue", secondary=["service_complaint_escalation"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Seller price hike ₹1300; 'criminal'."),
    2149534: dict(lang="en", primary="order_status_query", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="low", note="PO-box eligibility allowed at checkout but failed."),
    2747122: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="CS quality decreased; barely speak English."),
    1242242: dict(lang="en", primary="delivered_but_not_received", secondary=["service_complaint_escalation","product_return_and_replacement"],
        mtype="complaint", ctx="context_helpful", difficulty="hard", conf="medium", note="Investigated wrong item; package rob/investigation mess."),
    835153: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="Got a baniyan instead of the t-shirt."),
    2521823: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="self_contained", difficulty="easy", conf="high", note="No one reads customer service emails."),
    2909124: dict(lang="en", primary="other_unclear", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="low", note="Gift packaging not discreet; privacy complaint, no intent fits."),
    2679197: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="medium", note="Ask whether item was replaced (returns)."),
    2853614: dict(lang="en", primary="cancellation", secondary=[], mtype="support_request",
        ctx="self_contained", difficulty="easy", conf="high", note="Order went to cancelled; how to un-cancel."),
    972720: dict(lang="en", primary="refund_request", secondary=[], mtype="follow_up",
        ctx="context_required", difficulty="hard", conf="low", note="Current msg is promo text; context about courier refund."),
    2497106: dict(lang="en", primary="device_app_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="medium", note="App launched in India; expects English(India) language."),
    694411: dict(lang="en", primary="product_return_and_replacement", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="medium", conf="medium", note="Wants email to forward video re wrong product."),
    1845984: dict(lang="en", primary="charge_issue", secondary=[], mtype="follow_up",
        ctx="context_helpful", difficulty="hard", conf="medium", note="Amazon CC activated; promised voucher/authorisation."),
    1323314: dict(lang="en", primary="service_complaint_escalation", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="medium", conf="high", note="Replies when complaining are poor."),
    519702: dict(lang="en", primary="account_access", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="PSN codes wanted; account access flagged."),
    1568158: dict(lang="en", primary="charge_issue", secondary=[], mtype="complaint",
        ctx="context_helpful", difficulty="hard", conf="medium", note="MRP price discrepancy on items."),
}
